/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  /**
   * Table for storing groceries
   */
  groceries: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * The grocery item name
     */
    name: string;
    /**
     * The price of the grocery item
     */
    price: string;
    /**
     * The size of the container in which the item sits in
     */
    size: string;
    /**
     * A blurb about the product
     */
    description: string;
    /**
     * What goes into the product
     */
    ingredients: string;
    /**
     * Add tags to help it show up in search better
     */
    tags?: string;
    /**
     * The image for the item
     */
    imageUrl?: string;
  };
}
